# Generated by Django 5.1 on 2025-09-06 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgement',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='cases.case'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to=settings.AUTH_USER_MODEL),
        ),
    ]
